global:
  domain: ""
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "*"   
    paths:
      - path: /
        pathType: Prefix
  extraArgs:
    - --insecure
